### ISSUE TITLE
Verify challenge completion

### ISSUE THREAD

**Issue by MohammedMagamsey** [ICST-Technion/TechnionAsk#21]
## Value Statement
As a: client
I want to: be able to approve challenge completion for the other group member.
so I can: reward him with points in case of completion.

## Acceptance Criteria
* [ ]  Verify challenge completion functionality in app
* [ ]  Verify challenge completion  functionality in server
## Development Complete
* [ ]  Code is complete.
* [ ]  Functionality is working.
* [ ]  Any required downstream Docker file changes are made.
## Tests Automated
* [ ] Unit/function tests have been automated and incorporated into build.

**Comment by LaraKinan** [comment]
Project changed - irrelevant
