### ISSUE TITLE
Friend removal

### ISSUE THREAD

**Issue by MalikKhalaf4** [ICST-Technion/TechnionAsk#24]
## Value Statement
As a: client
I want to: be able to remove users from my friends list.
so I can: fully control who am I friends with.

## Acceptance Criteria
* [ ]  Friend removal functionality in app
* [ ]  Friend removal functionality in server
## Development Complete
* [ ]  Code is complete.
* [ ]  Functionality is working.
* [ ]  Any required downstream Docker file changes are made.
## Tests Automated
* [ ] Unit/function tests have been automated and incorporated into build.

**Comment by LaraKinan** [comment]
Project changed - irrelevant
