### ISSUE TITLE
Group removal

### ISSUE THREAD

**Issue by MalikKhalaf4** [ICST-Technion/TechnionAsk#25]
## Value Statement
As a: client
I want to: be able to delete groups that I previously created.
so I can: keep only relevant groups active.

## Acceptance Criteria
* [ ]  Group removal functionality in app
* [ ]  Group removal functionality in server
## Development Complete
* [ ]  Code is complete.
* [ ]  Functionality is working.
* [ ]  Any required downstream Docker file changes are made.
## Tests Automated
* [ ] Unit/function tests have been automated and incorporated into build.

**Comment by LaraKinan** [comment]
Project changed - irrelevant
