### ISSUE TITLE
Adding friends

### ISSUE THREAD

**Issue by MohammedMagamsey** [ICST-Technion/TechnionAsk#6]
## Value Statement
As a: client
I want to: be able to add other users as friends
so I can: create groups with them.

## Acceptance Criteria
* [ ]  Add Friend functionality in app
* [ ]  Add Friend functionality in server
## Development Complete
* [ ]  Code is complete.
* [ ]  Functionality is working.
* [ ]  Any required downstream Docker file changes are made.
## Tests Automated
* [ ] Unit/function tests have been automated and incorporated into build.

**Comment by LaraKinan** [comment]
Project changed - irrelevant
