### ISSUE TITLE
Challenge creation

### ISSUE THREAD

**Issue by MohammedMagamsey** [ICST-Technion/TechnionAsk#7]
## Value Statement
As a: client
I want to: create challenges in my group
so I can: push them to improve and have fun at the same time .

## Acceptance Criteria
* [ ]  create challenge functionality in app
* [ ]  create challenge functionality in server
## Development Complete
* [ ]  Code is complete.
* [ ]  Functionality is working.
* [ ]  Any required downstream Docker file changes are made.
## Tests Automated
* [ ] Unit/function tests have been automated and incorporated into build.

**Comment by LaraKinan** [comment]
Project changed - irrelevant
