### ISSUE TITLE
User search

### ISSUE THREAD

**Issue by MohammedMagamsey** [ICST-Technion/TechnionAsk#9]
## Value Statement
As a: client
I want to: be able to search for other users by their name
so I can: add them/create new group with them.

## Acceptance Criteria
* [ ]  search users functionality in app
* [ ]  search users functionality in server
## Development Complete
* [ ]  Code is complete.
* [ ]  Functionality is working.
* [ ]  Any required downstream Docker file changes are made.
## Tests Automated
* [ ] Unit/function tests have been automated and incorporated into build.

**Comment by LaraKinan** [comment]
Project changed - irrelevant
